# Pytorch Tensors
primero importamos la libreria de pytorch


In [1]:
import torch

Creamos un tensor de 2x3

In [2]:
x=torch.tensor([[1.0, 4.0, 7.0],[2.0,3.0,6.0]])
x

tensor([[1., 4., 7.],
        [2., 3., 6.]])

Podemos obtener la forma y el tipo de dato de esta forma

In [3]:
x.shape


torch.Size([2, 3])

In [4]:
x.dtype

torch.float32

la indexacion funciona como los arrays de numpy

In [5]:
x[0,1]

tensor(4.)

In [6]:
x[:,2]

tensor([7., 6.])

## operaciones con tensores

In [7]:
10*(x+10)

tensor([[110., 140., 170.],
        [120., 130., 160.]])

In [8]:
x.exp()

tensor([[   2.7183,   54.5981, 1096.6332],
        [   7.3891,   20.0855,  403.4288]])

In [9]:
x.mean()

tensor(3.8333)

In [10]:
x.max(dim=0) #los valores maximos de la dimension 0

torch.return_types.max(
values=tensor([2., 4., 7.]),
indices=tensor([1, 0, 0]))

In [11]:
x @ x.T  #matriz transpuesta y multiplicacion de matrices

tensor([[66., 56.],
        [56., 49.]])

## convertir de tensor a array de Numpy y viceversa

In [12]:
import numpy as np
x.numpy() #from tensor to numpy array

array([[1., 4., 7.],
       [2., 3., 6.]], dtype=float32)

In [13]:
torch.tensor(np.array([[1.,2.,3.],[4.,5.,6.]])) #from numpy array to tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

modificando un tensor

In [14]:
x[:,1]=-99
x

tensor([[  1., -99.,   7.],
        [  2., -99.,   6.]])

le podemos aplicar varias operacion como abs_(), sqr_() y zero_(), por ejemplo aca aplicamos el metodo ReLU

In [15]:
x.relu_()
x

tensor([[1., 0., 7.],
        [2., 0., 6.]])

# Harware Acceleration


chequeamos que pytorch tenga acceso a la GPU de Nvidia o al MPS de Apple de no ser asi volvemos a la CPU

In [16]:
if torch.cuda.is_available():
    device="cuda"
    print("Using GPU")
elif torch.backends.mps.is_available():
    device="mps"
    print("Using MPS")
else:
    device="cpu"
    print("Using CPU")

Using GPU


Creamos un tensor en la GPU

In [17]:
M=torch.tensor([[1.,2.,3.],[4.,5.,6.]])
M=M.to(device)

para saber en que device está un tensor podemos verlo

In [18]:
M.device

device(type='cuda', index=0)

Tambien podemos crear un tensor directamente en la GPU usando el argumento device

In [19]:
M=torch.tensor([[1.,2.,3.],[4.,5.,6.]], device=device)
M.device

device(type='cuda', index=0)

Una vez que el tensor este en la GPU podemos correr operaciones normalmente y ellas tomaran lugar en la GPU

In [20]:
R=M@M.T
R

tensor([[14., 32.],
        [32., 77.]], device='cuda:0')

# Autograd
Su función principal es calcular los gradientes (derivadas parciales) de forma automática aplicando la regla de la cadena, lo que permite entrenar redes neuronales sin necesidad de calcular derivadas a mano.


In [26]:
x=torch.tensor(5.0,requires_grad=True) #requires_grad=True es para decirle a pytorch que es una variable no una constante
f=x**2
f

tensor(25., grad_fn=<PowBackward0>)

In [27]:
f.backward()
x.grad

tensor(10.)

### gradient descent step
para hacerlo necesitamos situarlo dentro de torch.no_grad()

In [28]:
learning_rate=0.1
with torch.no_grad():
    x-=learning_rate*x.grad #gradient descent step

antes de que repitas el proceso es importante hacer zero los gradientes

In [29]:
x.grad.zero_()

tensor(0.)

poniendo todo junto el bucle de entrenamineto luciria asi

In [30]:
learning_rate=0.1
x=torch.tensor(8.0,requires_grad=True)
for i in range(100):
  f=x**2 #forward pass
  f.backward() #backward pass
  with torch.no_grad():
    x-=learning_rate*x.grad #gradiente descent step
  x.grad.zero_() #reset the gradient
